# Travel Analytics - WORKING dbt Project
# Initialize: dbt init
# Test connection: dbt debug
# Run models: dbt run

name: "travel_analytics"
version: "1.0.0"
config-version: 2

profile: "travel_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  travel_analytics:
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics
